### ISSUE TITLE
beater/mysqlbeat.go:289: b.Events undefined (type *beat.Beat has no field or method Events)

### ISSUE THREAD

**Issue by rinetd** [adibendahan/mysqlbeat#10]
./main.go:12: cannot use beater.New() (type *beater.Mysqlbeat) as type beat.Creator in argument to beat.Run

# github.com/adibendahan/mysqlbeat/beater
beater/mysqlbeat.go:289: b.Events undefined (type *beat.Beat has no field or method Events)
beater/mysqlbeat.go:303: b.Events undefined (type *beat.Beat has no field or method Events)
beater/mysqlbeat.go:326: b.Events undefined (type *beat.Beat has no field or method Events)

**Comment by adibendahan** [comment]
Please post more information...

**Comment by rinetd** [comment]
thankyou , the reason is i use the latest libbeat . because of GWF using glide tools I clone code just only from github repo

**Comment by rinetd** [comment]
https://www.elastic.co/guide/en/beats/libbeat/current/beater-interface.html
