### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by shantanuo** [adibendahan/mysqlbeat#11]
I am not able to install mysqlbeat. I have made sure that gopath is set.

> [root@localhost mysqlbeat]# make
> go build
> main.go:8:2: cannot find package "github.com/adibendahan/mysqlbeat/beater" in any of:
>         /home/go/src/github.com/adibendahan/mysqlbeat/beater (from $GOROOT)
>         ($GOPATH not set. For more details see: 'go help gopath')
> main.go:6:2: cannot find package "github.com/elastic/beats/libbeat/beat" in any of:
>         /home/go/src/github.com/elastic/beats/libbeat/beat (from $GOROOT)
>         ($GOPATH not set. For more details see: 'go help gopath')
> make: *** [build] Error 1

**Comment by shantanuo** [comment]
I was able to resolve the go path issue. But now I am getting different error...

```
[root@localhost mysqlbeat]# go get  github.com/adibendahan/mysqlbeat

# github.com/adibendahan/mysqlbeat/beater
/root/go/src/src/github.com/adibendahan/mysqlbeat/beater/mysqlbeat.go:289:7: b.Events undefined (type *beat.Beat has no field or method Events)
/root/go/src/src/github.com/adibendahan/mysqlbeat/beater/mysqlbeat.go:303:7: b.Events undefined (type *beat.Beat has no field or method Events)
/root/go/src/src/github.com/adibendahan/mysqlbeat/beater/mysqlbeat.go:326:5: b.Events undefined (type *beat.Beat has no field or method Events)

```

**Comment by shantanuo** [comment]
Now a different error :)

```
[root@localhost mysqlbeat]# make
go build
can't load package: /root/go/src/src/github.com/adibendahan/mysqlbeat/main.go:8:2: non-standard import "github.com/adibendahan/mysqlbeat/beater" in standard package "src/github.com/adibendahan/mysqlbeat"
make: *** [build] Error 1

```

**Comment by adibendahan** [comment]
Please post the solution for reference :)
