### ISSUE TITLE
How to update template?

### ISSUE THREAD

**Issue by shantanuo** [adibendahan/mysqlbeat#13]
When I added a new query, I got this error.

Start error: setup returned an error: error on config file, queries array length != queryTypes array length (each query should have a corresponding type on the same index)

How do I configure the template to include the results of the new query?

**Comment by adibendahan** [comment]
For every query you add you should add the querytype in a corresponding order on mysqlbeat.yaml


  # Defines the queries result types
  # 'single-row' will be translated as columnname:value
  # 'two-columns' will be translated as value-column1:value-column2 for each row
  # 'multiple-rows' each row will be a document (with columnname:value)
  # 'show-slave-delay' will only send the `Seconds_Behind_Master` column from SHOW SLAVE STATUS
  querytypes: ["two-columns",
               "show-slave-delay"]
