### ISSUE TITLE
Not getting data

### ISSUE THREAD

**Issue by jabolado** [adibendahan/mysqlbeat#4]
Some are not accurate or not getting the right data..

Sample:
QCACHE_HITS is getting only 1, but it should be 700000+..
Is this a problem with the _DELTA change from PERSECOND?

**Comment by adibendahan** [comment]
@jabolado I will check it out next week.

please try to provide more data:
run a query that will get the QCACHE_HITS value (at least twice, with 10 seconds differences) while the mysqbeat is running (and post the raw data as opposed to what the mysqlbeat calculates).

In addition, did you build from the current master or use the released version?

**Comment by stanxii** [comment]
Hi adibendahan. 
  yes I know the schema  test is test db now.  , 

But i can't get any data from mysql!  after running ./mysqlbeat -c mysqlbeat.yml
I only add a test table person in test db only id, name (var)  birthday(datetime) field.
querys set is 
 [ "SELECT NAME, birday FROM test.person"]

querytype  is multirows,
But I can't get any data! how to trace or debug to know where i promble?
thanks adibendabhan.

**Comment by adibendahan** [comment]
@stanxii see the logging and debugging options in the mysqlbeat.yml (inherited from original beat code)
