### ISSUE TITLE
index quantity are  4 times  of mysql db rows.

### ISSUE THREAD

**Issue by stanxii** [adibendahan/mysqlbeat#6]
Hi  i have a sql like select t1 a , b  from t1, t2  where...

mysql db has  2 rows.
But After mysqlbeat indexded into ES.  it has 8 document .

which every mysql row has 4 times  in ES. only different id!

How can do for fix this. 
Thanks.

**Comment by stanxii** [comment]
Which i mean is I want know 
If I only need update had  already indexed document!
How can i do, thanks.

**Comment by adibendahan** [comment]
@stanxii please provide the exact query you send and the data in both tables for further investigation.
