### ISSUE TITLE
Visualize: "field" is a required parameter

### ISSUE THREAD

**Issue by ghost** [adibendahan/mysqlbeat#7]
After completed the mysqlbeat installation when I try to view the new dashboards or its related visualizations for the mysqlbeat I get the following error: 
Saved "field" parameter is now invalid. Please select a new field.
Visualize: "field" is a required parameter

finally I decided to focus on the visualization "MySQL-InnoDB-I-slash-O" in order to try to figure out what is the problem:
so at the file mysql_performance_dashboard_by_mysqlbeat.json I see the following definition:
  {
    "_id": "MySQL-InnoDB-I-slash-O",
    "_type": "visualization",
    "_source": {
      "title": "MySQL - InnoDB I/O",
      "visState": "{\"title\":\"MySQL - InnoDB Buffer Pool Usage\",\"type\":\"area\",\"params\":{\"shareYAxis\":true,\"addTooltip\":true,\"addLegend\":true,\"smoothLines\":true,\"scale\":\"linear\",\"interpolate\":\"linear\",\"mode\":\"stacked\",\"times\":[],\"addTimeMarker\":false,\"defaultYExtents\":false,\"setYExtents\":false,\"yAxis\":{}},\"aggs\":[{\"id\":\"2\",\"type\":\"terms\",\"schema\":\"split\",\"params\":{\"field\":\"beat.name\",\"size\":10,\"order\":\"asc\",\"orderBy\":\"_term\",\"row\":true}},{\"id\":\"3\",\"type\":\"date_histogram\",\"schema\":\"segment\",\"params\":{\"field\":\"@timestamp\",\"interval\":\"auto\",\"customInterval\":\"2h\",\"min_doc_count\":1,\"extended_bounds\":{},\"customLabel\":\"Datetime\"}},{\"id\":\"5\",\"type\":\"max\",\"schema\":\"metric\",\"params\":{\"field\":\"INNODB_DATA_READS_PERSECOND\",\"customLabel\":\"Data Reads\"}},{\"id\":\"4\",\"type\":\"max\",\"schema\":\"metric\",\"params\":{\"field\":\"INNODB_DATA_WRITES_PERSECOND\",\"customLabel\":\"Data Writes\"}},{\"id\":\"1\",\"type\":\"max\",\"schema\":\"metric\",\"params\":{\"field\":\"INNODB_LOG_WRITES_PERSECOND\",\"customLabel\":\"Log Writes\"}},{\"id\":\"6\",\"type\":\"max\",\"schema\":\"metric\",\"params\":{\"field\":\"INNODB_DATA_FSYNCS_PERSECOND\",\"customLabel\":\"Data fsyncs\"}},{\"id\":\"7\",\"type\":\"max\",\"schema\":\"metric\",\"params\":{\"field\":\"INNODB_OS_LOG_FSYNCS_PERSECOND\",\"customLabel\":\"OS Log fsyncs\"}}],\"listeners\":{}}",
      "uiStateJSON": "{}",
      "description": "",
      "savedSearchId": "mysqlbeat",
      "version": 1,
      "kibanaSavedObjectMeta": {
        "searchSourceJSON": "{\"filter\":[]}"
      }
    }
  },
but at the mysqlbeat.yml I don't see where a queries contain the fields INNODB_LOG_WRITES_PERSECOND, INNODB_DATA_FSYNCS_PERSECON, INNODB_OS_LOG_FSYNCS_PERSECOND
Because it convert those fields name to a name with a surffix '__DELTA' and no where select that columns with the suffix  '_PERSECON'

  queries: [ "SELECT  CONCAT(VARIABLE_NAME, '__DELTA') AS VARIABLE_NAME, VARIABLE_VALUE
              FROM    information_schema.GLOBAL_STATUS
              WHERE   VARIABLE_NAME IN ('ABORTED_CONNECTS', 'CONNECTION_ERRORS_INTERNAL', 'CONNECTION_ERRORS_MAX_CONNECTIONS', 'CREATED_TMP_DISK_TABLES', 'CREATED_TMP_FILES',
                                         'CREATED_TMP_TABLES', 'HANDLER_COMMIT', 'HANDLER_ROLLBACK', 'HANDLER_SAVEPOINT', 'HANDLER_SAVEPOINT_ROLLBACK', 'INNODB_DATA_FSYNCS',
                                         'INNODB_DATA_READS', 'INNODB_DATA_WRITES', 'INNODB_LOG_WRITES', 'INNODB_OS_LOG_FSYNCS', 'INNODB_PAGES_CREATED', 'INNODB_PAGES_READ',
                                         'INNODB_PAGES_WRITTEN', 'INNODB_ROWS_DELETED', 'INNODB_ROWS_INSERTED', 'INNODB_ROWS_READ', 'INNODB_ROWS_UPDATED', 'INNODB_ROW_LOCK_TIME',
                                         'KEY_READS', 'KEY_READ_REQUESTS', 'KEY_WRITES', 'KEY_WRITE_REQUESTS', 'OPENED_TABLES', 'QCACHE_HITS', 'QCACHE_INSERTS', 'QCACHE_LOWMEM_PRUNES',
                                         'QCACHE_NOT_CACHED', 'SELECT_FULL_JOIN', 'SELECT_FULL_RANGE_JOIN', 'SELECT_RANGE', 'SELECT_RANGE_CHECK', 'SELECT_SCAN', 'SLOW_QUERIES',
                                         'SORT_MERGE_PASSES', 'SORT_RANGE', 'SORT_ROWS', 'SORT_SCAN', 'TABLE_LOCKS_IMMEDIATE', 'TABLE_LOCKS_WAITED', 'INNODB_ROW_LOCK_WAITS')
              UNION
              SELECT  VARIABLE_NAME, VARIABLE_VALUE
              FROM    information_schema.GLOBAL_VARIABLES
              WHERE   VARIABLE_NAME IN ('MAX_CONNECTIONS', 'TABLE_OPEN_CACHE')
              UNION
              SELECT  VARIABLE_NAME, VARIABLE_VALUE
              FROM    information_schema.GLOBAL_STATUS
              WHERE   VARIABLE_NAME IN ('INNODB_BUFFER_POOL_PAGES_DATA', 'INNODB_BUFFER_POOL_PAGES_FREE', 'INNODB_BUFFER_POOL_PAGES_TOTAL', 'OPEN_FILES', 'OPEN_TABLES',
                                        'QCACHE_QUERIES_IN_CACHE', 'THREADS_CONNECTED', 'THREADS_RUNNING', 'INNODB_PAGE_SIZE')
              UNION
              SELECT  'INNODB_BUFFER_POOL_HIT_RATIO' AS VARIABLE_NAME,
                      INNODB_BUFFER_POOL_READ_REQUESTS.VARIABLE_VALUE  / (INNODB_BUFFER_POOL_READ_REQUESTS.VARIABLE_VALUE  + INNODB_BUFFER_POOL_READS.VARIABLE_VALUE) * 100 AS VARIABLE_VALUE
              FROM    information_schema.GLOBAL_STATUS INNODB_BUFFER_POOL_READS, information_schema.GLOBAL_STATUS INNODB_BUFFER_POOL_READ_REQUESTS
              WHERE   INNODB_BUFFER_POOL_READS.variable_name ='INNODB_BUFFER_POOL_READS' AND
                      INNODB_BUFFER_POOL_READ_REQUESTS.variable_name ='INNODB_BUFFER_POOL_READ_REQUESTS'
              UNION
              SELECT  'CONST_100' AS VARIABLE_NAME, 100 AS VARIABLE_VALUE",
             "SHOW SLAVE STATUS"]

From where does it suppose to get the columns with the suffix  '_PERSECON'?

Thank you,
Ofir

**Comment by adibendahan** [comment]
Hi @OfirGranot,
The mysqlbeat code replaces the names of the columns that end with the "delta wildcard" and adds the _PERSECOND automatically. So any column from the following query will be replaced:

`SELECT CONCAT(VARIABLE_NAME, '__DELTA') AS VARIABLE_NAME, VARIABLE_VALUE 
FROM information_schema.GLOBAL_STATUS ... `

for example INNODB_DATA_WRITES_DELTA will be replaced to INNODB_DATA_WRITES_PERSECOND after the calculation will be made.

-- Adi.

**Comment by ghost** [comment]
Hi Adi,

I analyzed it after I posted my question (sorry that I forgot to update you then), the beat load failed because it tried to load the data with _DELTA suffix instead of _PERSECOND suffix to match the index pattern and the visualization queries, in order to make it work I changed the mysqlbeat.yml as following:
1.  queries: [ "SELECT  CONCAT(VARIABLE_NAME, '_PERSECOND') AS VARIABLE_NAME, VARIABLE_VALUE
              FROM    information_schema.GLOBAL_STATUS
2. Appended for suffix _PERSECOND - after I compared with that mysqlbeat.yml file at the mysqlbeat-master zip:
   # Colums that end with the following wild card will report only delta in seconds ((neval - oldval)/timediff.Seconds())
  #deltawildcard: "__DELTA"
  deltawildcard: "_PERSECOND"
3. Modified deltakeywildcard for suffix PERSECOND:
deltakeywildcard: "_PERSECONDKEY"

And now the mysqlbeat dashboard visualizations work properly for me.
