### ISSUE TITLE
[help needed] Managing deltas

### ISSUE THREAD

**Issue by Bichonche** [adibendahan/mysqlbeat#9]
Hello,

I am currently trying to use your custom beat.  When trying to pull data from my DB everything runs smoothly, except for one thing. I can't figure out how to only update my indexes only with new or modified content. I considered these queries : 
 ```
queries: [ "SELECT THE_ID,
    THE_USER, 
    THE_DATE FROM    thetable.USER"]
```

This one doesnt work for obvious reasons, but these two don't either :
```
queries: [ "SELECT THE_ID, 
    THE_USER, 
    CONCAT(THE_DATE, '__DELTA') AS THE_DATE 
    FROM    thetable.USER"]
```

```
queries: [ "SELECT CONCAT(THE_ID, '__DELTAKEY), 
    THE_USER, 
    CONCAT(THE_DATE, '__DELTAKEY') AS THE_DATE 
    FROM    thetable.USER"]
```

I was hoping maybe you could help me out on this issue, wether that's because I misundestrood your documentation, or you didn't incorporate these kind of delta's in the beat.

Thanks !

**Comment by adibendahan** [comment]
Currently mysqlbeat only supports Integer/Float as delta columns... sorry about that.
